"""Generate user-local .desktop files with KDE jump-list actions.

Follows the same pattern KDE Kate uses: copy the vendor desktop entry into
``~/.local/share/applications`` (preserving identity: Exec, StartupWMClass,
MimeType, Icon), then append ``Actions=`` groups. Plasma's task manager reads
these via KService and shows them in the icon context menu.

Actions invoke ``kde-vscode-jumplist open <entry-id>``; the ID is resolved
from the entry store, so no URIs or quoting-sensitive data appear in Exec
lines. The trailing "Manage Pinned Files…" entry invokes ``manage`` instead,
which opens the pinning dialog.

The launcher baked into those Exec lines is verified before use: Plasma and
systemd do not inherit the environment the sync ran in (notably PYTHONPATH),
so a command is only accepted if it starts this CLI without it. Each action also
carries ``--config <file>``, for the same reason: a click is a plain process
launch, whose working directory need not be the one the menu was generated in.
"""

from __future__ import annotations

import configparser
import logging
import os
import shutil
import subprocess
import sys
from pathlib import Path

from . import APP_NAME, __version__
from . import config
from . import paths
from .models import ENTRY_FILE, ENTRY_FOLDER, MenuEntry
from .util import atomic_write_text

log = logging.getLogger(__name__)

# Importable module name, used by the ``<python> -m <MODULE>`` fallback when
# the console script is not on PATH.
MODULE = "kde_vscode_jumplist"

# Program name: console script, built ``bin/`` executable, systemd unit name.
# The same string as the package's APP_NAME, defined once there.
PROG = APP_NAME

# Action ids must be spec-safe (no spaces); groups are written as
# "[Desktop Action <id>]" — the only form KService recognizes.
ACTION_PREFIX = "KdeVsCodeJumpList-"
# Prefixes written by older versions. They must stay recognized so stale
# actions are cleaned up on regeneration, and so an old generated file is
# still detected as ours instead of being mistaken for a vendor file:
#   "KdeVsCodeMenu-"  pre-rename, when the project was called kde-vscode-menu
#   "KdeVsCodeMenu "  pre-0.2 "[KdeVsCodeMenu Recent <id>]" groups with spaces
#                     in the id, which KService silently dropped
LEGACY_ACTION_PREFIXES = ("KdeVsCodeMenu-", "KdeVsCodeMenu ")
# Group headers to drop on regeneration: current + legacy, in both the bare
# (pre-0.2) and the "[Desktop Action <id>]" form.
_OUR_SECTION_PREFIXES = tuple(
    "Desktop Action " + prefix for prefix in (ACTION_PREFIX, *LEGACY_ACTION_PREFIXES)
) + LEGACY_ACTION_PREFIXES
GENERATED_MARKER = "# Generated by kde-vscode-jumplist - do not edit"
LEGACY_GENERATED_MARKER = "# Generated by kde-vscode-menu - do not edit"
MAX_PINNED = 10

# KService's native menu separator: an action id of "_SEPARATOR_" in Actions=
# becomes a KServiceAction with isSeparator() == true, which Plasma's task
# manager renders as a horizontal line (Backend::jumpListActions calls
# QAction::setSeparator(true)). It needs no matching desktop action group.
SEPARATOR = "_SEPARATOR_"

# Section captions imitating Dolphin's headings. A separator cannot carry
# text, so each caption is a real (but inert) action placed directly under the
# separator that opens its block. The ids deliberately avoid the "Pinned-" and
# "Recent-" prefixes so per-entry lookups never match them.
PINNED_CAPTION_ACTION_ID = ACTION_PREFIX + "Caption-Pinned"
PINNED_CAPTION_TEXT = "Pinned Files:"
# Bookmark metaphor (matching Dolphin/Kate).
PINNED_CAPTION_ICON = "bookmarks"
RECENT_CAPTION_ACTION_ID = ACTION_PREFIX + "Caption"  # id kept for older files
# Plural, to match the pinned heading ("Pinned Files:").
RECENT_CAPTION_TEXT = "Recent Files:"
# A plain clock reads as "recent" without the open-document overlay that
# "document-open-recent" carries. Both are Breeze actions at 16/22/24px, and
# distinct from PINNED_CAPTION_ICON so a heading is never mistaken for one
# another (tests assert that).
RECENT_CAPTION_ICON = "clock"
# Clicking a caption must be harmless: /bin/true exits 0 and does nothing.
NOOP_EXEC = "/bin/true"

# The manager entry, which opens the pinning dialog. It is written after every
# other action of ours, and Plasma appends its own task-manager entries
# ("Pin to Task Manager" / "Unpin from Task Manager") after the whole Actions=
# list, so this placeholder is what lands directly above them. It is emitted
# unconditionally, including when there is nothing to list, because it is the
# only way to pin anything from the menu.
MANAGE_ACTION_ID = ACTION_PREFIX + "Manage"
MANAGE_TEXT = "Manage Pinned Files\u2026"
# Distinct from PINNED_CAPTION_ICON ("bookmarks"), so the entry is never
# mistaken for the heading whose block it closes.
MANAGE_ICON = "bookmark-new"

# How many recent entries (after the kind exclusions below, in MRU order) are
# listed, and which kinds are left out: the `max_recents` and `exclude_kinds`
# settings in config.toml. Workspaces are excluded by default (a .code-workspace
# mostly repeats a folder that is already listed, and opening one is a different
# action from opening the folder), an empty list keeps every kind, and pinned
# entries are never filtered.

# Icon name per entry kind. The names must exist in the usual icon themes
# (Breeze, hicolor): Plasma shows a placeholder for a name it cannot resolve,
# which reads as a broken menu.
#
# Workspaces deliberately have no entry: there is no "workspace" icon in Breeze,
# and recents exclude that kind by default anyway, so they fall back to
# DEFAULT_ICON rather than getting an invented name.
DEFAULT_ICON = "text-x-generic"
ICON_FOR_KIND = {
    ENTRY_FOLDER: "folder",
    ENTRY_FILE: DEFAULT_ICON,
}

# Pinned entries all share one icon, replacing the per-kind one: the star is
# what marks the entry as a pinned one at a glance, which the folder/file icon
# cannot show. "starred" is Breeze's filled star (16/22/24px).
PINNED_ICON = "starred"


def max_recents() -> int:
    """Total recent-entries limit, from the configuration at call time."""
    return config.current().max_recents


def excluded_kinds() -> frozenset[str]:
    """Entry kinds to leave out of the recents list, at call time.

    An absent key gives the default (workspaces); an empty list means "exclude
    nothing", so the default is opt-out rather than impossible to disable.
    """
    return config.current().exclude_kinds


def keep_recent(entries: list[MenuEntry]) -> list[MenuEntry]:
    """Drop excluded kinds, preserving MRU order."""
    excluded = excluded_kinds()
    return [entry for entry in entries if entry.kind not in excluded]


def pinned_position() -> str:
    """``pinned_position`` normalized to "above" or "below".

    Which block comes first in the menu: the accepted spellings and the default
    both live in :mod:`kde_vscode_jumplist.config`.
    """
    return config.current().pinned_position


def pinned_below_recents() -> bool:
    """True when the pinned block should be listed after the recents."""
    return pinned_position() == "below"


def config_arguments() -> list[str]:
    """Arguments naming this run's configuration file.

    Used by everything that starts the CLI without an inherited environment: a
    menu action and the systemd unit are both plain process launches. They also
    start in a working directory of their own, so ``./config.toml`` may not be
    the file the menu was generated from -- naming it outright is what stops a
    click from reading a different configuration, or none at all.
    """
    return ["--config", str(config.current().path)]


def desktop_launcher_command() -> str:
    """``Exec=``-ready launcher for the desktop actions.

    The verified launcher, followed by the configuration file it was generated
    with. Clicks regenerate the menu through this same command, so a click that
    resolved a different configuration would rewrite the menu from settings the
    user never chose.
    """
    return format_exec([*resolve_cli_argv(), *config_arguments()])


def _sanitize_label(label: str) -> str:
    """Escape characters that are special in desktop-entry values."""
    return label.replace("\\", "\\\\").replace("\n", " ").strip() or "Untitled"


def _action_name(entry: MenuEntry, pinned: bool) -> str:
    prefix = "Pinned" if pinned else "Recent"
    return f"{ACTION_PREFIX}{prefix}-{entry.entry_id}"


# Characters the Desktop Entry Specification reserves inside an Exec argument.
# An argument containing any of them (or whitespace) has to be quoted.
EXEC_RESERVED_CHARS = frozenset(" \t\n\"'\\><~|&;$*#()?!`%")


def format_exec(arguments: list[str]) -> str:
    """Join argv into an ``Exec=`` value, quoting as the spec requires.

    ``shlex.join`` cannot be used here: single quotes are literal in Exec
    values, so quoting is done with double quotes and backslash escapes.
    """
    formatted: list[str] = []
    for argument in arguments:
        if argument and not (EXEC_RESERVED_CHARS & set(argument)):
            formatted.append(argument)
            continue
        escaped = (
            argument.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("`", "\\`")
            .replace("$", "\\$")
        )
        formatted.append(f'"{escaped}"')
    return " ".join(formatted)


def module_source_root() -> Path | None:
    """Directory to put on PYTHONPATH so ``python -m kde_vscode_jumplist`` works.

    Non-``None`` only when this package sits in a plain ``.../<root>/kde_vscode_jumplist``
    layout that can be re-imported by pointing PYTHONPATH at the parent.
    """
    root = Path(__file__).resolve().parent.parent
    return root if (root / MODULE).is_dir() else None


def packaged_cli_path() -> Path | None:
    """The single-file executable built by ``make build``, when present.

    Self-contained, so it is the most dependable thing to bake into an Exec:
    it needs no PYTHONPATH, no virtualenv and no ``PATH`` entry.
    """
    source_root = module_source_root()
    if source_root is None:
        return None
    candidate = source_root.parent / "bin" / PROG
    return candidate if candidate.is_file() else None


def _running_program() -> list[str] | None:
    """The program running right now, if it can be re-run to start the CLI.

    Catches the common cases where the CLI was invoked through a launcher we
    would otherwise have to guess at: the built ``bin/`` executable, or a
    console script. Verification rejects the ones that cannot be re-run (a
    ``python -m`` run leaves ``sys.argv[0]`` pointing at ``__main__.py``).
    """
    if not sys.argv or not sys.argv[0]:
        return None
    program = Path(sys.argv[0])
    if program.is_file() and os.access(program, os.X_OK):
        return [str(program.resolve())]
    return None


def installed_cli_path() -> Path | None:
    """The executable ``install`` placed in the user's bin directory, if any.

    Preferred over everything else but the running program: unlike a build
    artifact in a working tree, it stays valid when the checkout moves.
    """
    candidate = paths.user_bin_dir() / PROG
    return candidate if candidate.is_file() else None


def _candidate_cli_commands(python: str | None = None) -> list[list[str]]:
    """Ways to launch the CLI, most desirable first.

    Installed and built executables are self-contained, so their commands can
    never break later; the interpreter-based fallbacks come last.
    """
    interpreter = python or sys.executable
    candidates: list[list[str]] = []

    running = _running_program()
    if running:
        candidates.append(running)

    installed = installed_cli_path()
    if installed is not None:
        candidates.append([str(installed)])

    console_script = shutil.which(PROG)
    if console_script:
        candidates.append([console_script])

    packaged = packaged_cli_path()
    if packaged is not None:
        candidates.append([str(packaged)])

    candidates.append([interpreter, "-m", MODULE])

    # A source checkout (``make update``) only imports the package because the
    # caller exported PYTHONPATH. Plasma and systemd do not, so bake the import
    # path into the Exec; without this the action would silently do nothing.
    env_binary = shutil.which("env")
    source_root = module_source_root()
    if env_binary and source_root is not None:
        candidates.append([env_binary, f"PYTHONPATH={source_root}", interpreter, "-m", MODULE])

    # ``which`` may well return the installed copy again; probing it twice only
    # costs a subprocess.
    deduplicated: list[list[str]] = []
    seen: set[str] = set()
    for candidate in candidates:
        key = os.path.realpath(candidate[0])
        if key in seen:
            continue
        seen.add(key)
        deduplicated.append(candidate)
    return deduplicated


def launcher_environment() -> dict[str, str]:
    """Environment approximating a Plasma/systemd launch.

    PYTHONPATH/PYTHONHOME are dropped so a candidate is only accepted when it
    works *without* the sync process's own import path.
    """
    environment = dict(os.environ)
    environment.pop("PYTHONPATH", None)
    environment.pop("PYTHONHOME", None)
    return environment


def _command_launches_cli(command: list[str]) -> bool:
    """True when ``command`` starts *this* CLI from a Plasma-like environment.

    The version is compared, not just the exit status: on its own, ``--version``
    is satisfied by any number of unrelated programs (``python``, ``pytest``),
    and baking one of those into an Exec would be worse than no action at all.
    """
    try:
        result = subprocess.run(  # noqa: S603 - argv list, no shell
            [*command, "--version"],
            env=launcher_environment(),
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            timeout=60,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    return result.returncode == 0 and result.stdout.strip() == __version__


def resolve_cli_argv(python: str | None = None) -> list[str]:
    """argv prefix that reliably launches this CLI outside the sync process.

    Candidates are *verified*: a click is useless if the interpreter cannot
    import the package, so broken candidates (e.g. ``/usr/bin/python3`` when
    the package is only on the caller's PYTHONPATH) are skipped.
    """
    candidates = _candidate_cli_commands(python)
    for command in candidates:
        if _command_launches_cli(command):
            return command
    log.error(
        "no working way to launch the CLI found; jump-list actions will do "
        "nothing when clicked (tried: %s)",
        ", ".join(format_exec(command) for command in candidates),
    )
    return candidates[-1]


def resolve_cli_command(python: str | None = None) -> str:
    """``Exec=``-ready command prefix returned by :func:`resolve_cli_argv`."""
    return format_exec(resolve_cli_argv(python))


def _exec_line(entry_id: str, cli_command: str) -> str:
    return f"{cli_command} open {entry_id}"


def _add_caption_group(
    parser: configparser.RawConfigParser,
    action_id: str,
    text: str,
    icon: str,
) -> str:
    """Write one inert section caption; returns its action id."""
    section = f"Desktop Action {action_id}"
    parser.add_section(section)
    parser.set(section, "Name", text)
    parser.set(section, "Icon", icon)
    parser.set(section, "Exec", NOOP_EXEC)
    return action_id


def _add_manage_group(parser: configparser.RawConfigParser, cli_command: str) -> str:
    """Write the Manager action; returns its action id.

    Unlike the captions this one really launches something, so it carries the
    same verified launcher as the entry actions rather than NOOP_EXEC.
    """
    section = f"Desktop Action {MANAGE_ACTION_ID}"
    parser.add_section(section)
    parser.set(section, "Name", MANAGE_TEXT)
    parser.set(section, "Icon", MANAGE_ICON)
    parser.set(section, "Exec", f"{cli_command} manage")
    return MANAGE_ACTION_ID


def build_desktop_content(
    base_content: str,
    pinned: list[MenuEntry],
    recents: list[MenuEntry],
) -> str:
    """Return the full desktop-file text with jump-list actions appended.

    ``pinned`` (the pinned entries) and ``recents`` each become their own block,
    opened by a native separator and an inert caption ("Pinned Files:" /
    "Recent Files:"); a block is omitted when its list is empty. ``recents`` is
    a single MRU-ordered list of any kind; kinds in :func:`excluded_kinds`
    (workspaces by default) are dropped, and at most ``max_recents()`` of the
    rest are listed. Pinned entries are never filtered, so a pinned workspace
    still appears.
    """
    parser = configparser.RawConfigParser(strict=False, interpolation=None)
    parser.optionxform = str  # preserve key case
    parser.read_string(base_content)

    if not parser.has_section("Desktop Entry"):
        raise ValueError("vendor desktop file has no [Desktop Entry] section")

    # Remove previously generated actions and their groups, keep others.
    # Covers both the current and the legacy (space-separated) naming.
    existing_actions = parser.get("Desktop Entry", "Actions", fallback="")
    raw_actions = [a.strip() for a in existing_actions.split(";") if a.strip()]

    def is_ours(name: str) -> bool:
        return name.startswith(ACTION_PREFIX) or name.startswith(LEGACY_ACTION_PREFIXES)

    kept_actions: list[str] = []
    for index, name in enumerate(raw_actions):
        if is_ours(name):
            continue
        if name == SEPARATOR:
            # Only drop the separators we added around our own block, so a
            # vendor-supplied separator elsewhere in Actions= survives.
            after_ours = index > 0 and is_ours(raw_actions[index - 1])
            before_ours = index + 1 < len(raw_actions) and is_ours(raw_actions[index + 1])
            if after_ours or before_ours:
                continue
        kept_actions.append(name)

    for section in list(parser.sections()):
        if section.startswith(_OUR_SECTION_PREFIXES):
            parser.remove_section(section)

    # Verified once per generation pass (spawns a probe process), then reused
    # by every action so all of them are clickable from Plasma.
    cli_command = desktop_launcher_command()

    def add_group(entry: MenuEntry, pinned: bool) -> str:
        """Write one desktop action group; returns its action id."""
        name = _action_name(entry, pinned)
        # KService only recognizes groups named "[Desktop Action <id>]".
        section = f"Desktop Action {name}"
        parser.add_section(section)
        # No "[pinned]" suffix: the block heading and the star icon already say
        # it, and the label stays clean.
        parser.set(section, "Name", _sanitize_label(entry.label))
        icon = PINNED_ICON if pinned else ICON_FOR_KIND.get(entry.kind, DEFAULT_ICON)
        parser.set(section, "Icon", icon)
        parser.set(section, "Exec", _exec_line(entry.entry_id, cli_command))
        return name

    limit = max_recents()

    def pinned_block() -> list[str]:
        """Separator, heading and pinned entries -- empty when nothing is pinned."""
        entries = [add_group(entry, pinned=True) for entry in pinned[:MAX_PINNED]]
        if not entries:
            return []
        return [
            SEPARATOR,
            _add_caption_group(
                parser,
                PINNED_CAPTION_ACTION_ID,
                PINNED_CAPTION_TEXT,
                PINNED_CAPTION_ICON,
            ),
            *entries,
        ]

    def recents_block() -> list[str]:
        """Separator, heading and recent entries -- empty when nothing recent.

        Excluded kinds (workspaces by default) are dropped before the limit is
        applied, so the limit counts only entries that actually get listed.
        """
        entries = [add_group(entry, pinned=False) for entry in keep_recent(recents)[:limit]]
        if not entries:
            return []
        return [
            SEPARATOR,
            _add_caption_group(
                parser,
                RECENT_CAPTION_ACTION_ID,
                RECENT_CAPTION_TEXT,
                RECENT_CAPTION_ICON,
            ),
            *entries,
        ]

    blocks = (
        [recents_block(), pinned_block()]
        if pinned_below_recents()
        else [pinned_block(), recents_block()]
    )
    new_actions = [action for block in blocks for action in block]

    # Close the last block with a separator, so the list ends with a line rather
    # than butting up against the bottom of the menu. Emitted only when there is
    # something above it to close off.
    if new_actions:
        new_actions.append(SEPARATOR)

    # Last of all, so it sits between our blocks and Plasma's own entries.
    new_actions.append(_add_manage_group(parser, cli_command))

    all_actions = kept_actions + new_actions
    parser.set("Desktop Entry", "Actions", ";".join(all_actions) + ";")

    from io import StringIO

    output = StringIO()
    parser.write(output, space_around_delimiters=False)
    return GENERATED_MARKER + "\n" + output.getvalue()


def is_generated(path: Path) -> bool:
    """True when a desktop file was written by this tool (not a vendor file).

    Detects the marker comment (current or pre-rename) and, for files written
    before the marker existed, any generated action section.
    """
    try:
        content = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    if content.startswith((GENERATED_MARKER, LEGACY_GENERATED_MARKER)):
        return True
    return any(
        f"[{prefix}" in content or f"[Desktop Action {prefix}" in content
        for prefix in (ACTION_PREFIX, *LEGACY_ACTION_PREFIXES)
    )


def write_user_desktop_entry(
    installation_desktop: Path,
    variant: str,
    pinned: list[MenuEntry],
    recents: list[MenuEntry],
) -> Path | None:
    """Copy + extend the vendor desktop file into the user applications dir.

    Returns the written path, or ``None`` when nothing changed / not possible.
    """
    if not installation_desktop.is_file():
        log.warning("vendor desktop file missing: %s", installation_desktop)
        return None

    base_content = installation_desktop.read_text(encoding="utf-8", errors="replace")
    try:
        content = build_desktop_content(base_content, pinned, recents)
    except (ValueError, configparser.Error) as error:
        log.error("cannot generate desktop entry for %s: %s", variant, error)
        return None

    target = paths.user_applications_dir() / installation_desktop.name
    if target.is_file() and target.read_text(encoding="utf-8", errors="replace") == content:
        return None  # unchanged — avoid expensive ksycoca rebuilds

    if installation_desktop.resolve() == target.resolve():
        log.error("refusing to overwrite vendor desktop file %s", target)
        return None

    target.parent.mkdir(parents=True, exist_ok=True)
    atomic_write_text(target, content)
    log.info("wrote %s", target)
    return target


def refresh_service_cache() -> None:
    """Rebuild the KDE service cache so Plasma picks up new actions."""
    for tool in ("kbuildsycoca6", "kbuildsycoca5"):
        binary = shutil.which(tool)
        if binary:
            try:
                subprocess.run(  # noqa: S603
                    [binary],
                    check=False,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    timeout=60,
                )
                log.info("refreshed service cache via %s", tool)
            except (OSError, subprocess.TimeoutExpired) as error:
                log.warning("%s failed: %s", tool, error)
            return
    log.warning("no kbuildsycoca found; Plasma may show stale menu entries")
