"""Generate user-local .desktop files with KDE jump-list actions.

Follows the same pattern KDE Kate uses: copy the vendor desktop entry into
``~/.local/share/applications`` (preserving identity: Exec, StartupWMClass,
MimeType, Icon), then append ``Actions=`` groups. Plasma's task manager reads
these via KService and shows them in the icon context menu.

Actions invoke ``kde-vscode-jumplist open <entry-id>``; the ID is resolved
from the entry store, so no URIs or quoting-sensitive data appear in Exec
lines. The "Pinned Files:" heading invokes ``manage`` instead, which opens the
pinning dialog -- so the heading is both a heading and the way in, rather than
a heading plus a separate entry further down the menu.

The launcher baked into those Exec lines is verified before use: Plasma and
systemd do not inherit the environment the sync ran in (notably PYTHONPATH),
so a command is only accepted if it starts this CLI without it.
"""

from __future__ import annotations

import configparser
import logging
import os
import shutil
import subprocess
import sys
from io import StringIO
from pathlib import Path

from . import APP_NAME, __version__
from . import paths
from .models import ENTRY_FILE, ENTRY_FOLDER, ENTRY_WORKSPACE, MenuEntry
from .util import atomic_write_text

log = logging.getLogger(__name__)

# Importable module name, used by the ``<python> -m <MODULE>`` fallback when
# the console script is not on PATH.
MODULE = "kde_vscode_jumplist"

# Action ids must be spec-safe (no spaces); groups are written as
# "[Desktop Action <id>]" — the only form KService recognizes.
ACTION_PREFIX = "KdeVsCodeJumpList-"
# Prefixes an older release wrote, in both its spellings: the plain one, and the
# pre-spec "[KdeVsCodeMenu Recent <id>]" form with spaces in the id, which
# KService silently drops. They must stay recognized so stale actions are cleaned
# up on regeneration, and so an old generated file is detected as ours rather
# than mistaken for a vendor file.
LEGACY_ACTION_PREFIXES = ("KdeVsCodeMenu-", "KdeVsCodeMenu ")
# Group headers to drop on regeneration: current + legacy, in both the bare
# and the "[Desktop Action <id>]" form.
_OUR_SECTION_PREFIXES = tuple(
    "Desktop Action " + prefix for prefix in (ACTION_PREFIX, *LEGACY_ACTION_PREFIXES)
) + LEGACY_ACTION_PREFIXES
GENERATED_MARKER = "# Generated by kde-vscode-jumplist - do not edit"
# The marker an older release wrote. Kept so files it generated are still
# recognized as ours.
LEGACY_GENERATED_MARKER = "# Generated by kde-vscode-menu - do not edit"

# How many entries the two blocks may hold together. The pinned entries are
# listed first and in full, and the recents fill whatever is left, so the jump
# list stays a predictable length however much is pinned.
TOTAL_ENTRIES = 12

# Entry kinds left out of the recents list. A .code-workspace mostly repeats a
# folder that is already listed, and opening one is a different action from
# opening the folder. Pinned entries are never filtered, so a pinned workspace
# still appears.
EXCLUDED_KINDS = frozenset({ENTRY_WORKSPACE})

# Which block comes first in the menu: True lists the pinned entries after the
# recents, False above them.
PINNED_BELOW = True

# KService's native menu separator: an action id of "_SEPARATOR_" in Actions=
# becomes a KServiceAction with isSeparator() == true, which Plasma's task
# manager renders as a horizontal line (Backend::jumpListActions calls
# QAction::setSeparator(true)). It needs no matching desktop action group.
SEPARATOR = "_SEPARATOR_"

# Section captions imitating Dolphin's headings. A separator cannot carry
# text, so each caption is a real action placed directly under the separator
# that opens its block. The ids deliberately avoid the "Pinned-" and
# "Recent-" prefixes so per-entry lookups never match them.
#
# The pinned heading doubles as the way into the manager: clicking it opens the
# dialog that pins, unpins and reorders, so there is no separate "Manage Pinned
# Files" entry to go looking for. Its icon is the manager's own -- a bookmark
# with a plus, which reads as "add to this list".
#
# A marker after the text stands in for the arrow a submenu row carries, so the
# heading reads as clickable, and it is pushed to the right edge with padding.
#
# A Qt menu draws each item's text from a fixed left inset, so the only way to
# reach the right edge is for the heading to be the widest item in the menu: the
# padding below is sized off the longest label so that it always is, and the
# marker then sits at the content's right edge -- 21px from the border, against
# 28px when the text ends at the shortcut column instead.
#
# The pad is sized off the longest label rather than being a fixed number, and
# only off the part of it that has to be made up: the heading already carries
# PINNED_CAPTION_BASE, so that much width is free. Charging for it again would
# only widen the menu -- padding the heading past the point where it is already
# the widest item cannot move the marker any further right, because the marker
# sits at whatever the widest item's width ends up being.
#
# The margin in PINNED_CAPTION_PAD_FREE is what keeps the estimate safe. A
# character count is a rough proxy for width -- a space is narrower than an
# average label character, which is the whole reason the ratio is above 1 -- so
# the arithmetic cannot be exact without font metrics, which this module does not
# have (Qt is optional). Measured against real path-like labels, the marker
# reaches the content edge (23-24px from the border) for every length up to ~50
# characters. Past that it falls a few px short, which is the graceful direction
# to be wrong in: the heading stops being the widest item, the marker drifts
# slightly in, and the menu stays as narrow as the label requires.
#
# Trailing spaces are safe to use here only because the marker follows them --
# KConfig and QMenu both trim *trailing* whitespace, so padding placed after the
# marker would be discarded.
#
# The glyph is U+25B9 WHITE RIGHT SMALL TRIANGLE: a hollow arrow head. Hollow
# rather than solid because at this size a filled triangle reads as a bullet
# rather than as an arrow, and because the outline matches the outlined style of
# the surrounding chrome. It is the small variant of U+25B7, so it has the same
# open shape and stroke weight one size down -- a size that suits a menu row
# better than the medium one. Measured in the menu font (11pt Ubuntu Sans, on a
# menu row 29px tall), the right-pointing candidates render: U+203A 3x7, U+232A
# 3x11, U+22B3 7x6, U+25B9 7x8, U+2BC7 8x8, U+300B 7x11, U+25B7 10x12 and the
# solid U+25B6 11x12. It draws in the theme's text colour, not as a colour emoji.
#
# A real arrow is not available. The style draws one only for an action that has
# a submenu, and a desktop action cannot have one: KServiceAction carries Name,
# Icon, Exec and NoDisplay and nothing else, and the task manager turns each one
# into a bare QAction -- see Backend::jumpListActions in
# applets/taskmanager/backend.cpp, which never calls setMenu.
PINNED_CAPTION_ACTION_ID = ACTION_PREFIX + "Caption-Pinned"
PINNED_CAPTION_BASE = "Pinned Files:"
PINNED_CAPTION_MARKER = "\u25b9"
# How much padding to add, per character of the longest entry label: a space is
# narrower than an average label character, so more than one is needed per
# character to make up the difference.
PINNED_CAPTION_PAD_RATIO = 2
# Characters of the longest label the heading already covers for free, by being
# PINNED_CAPTION_BASE wide, plus a small margin. See the note above.
PINNED_CAPTION_PAD_FREE = 12
PINNED_CAPTION_ICON = "bookmark-new"
RECENT_CAPTION_ACTION_ID = ACTION_PREFIX + "Caption"
# Plural, to match the pinned heading ("Pinned Files:").
RECENT_CAPTION_TEXT = "Recent Files:"
# A plain clock reads as "recent" without the open-document overlay that
# "document-open-recent" carries. Both are Breeze actions at 16/22/24px, and
# distinct from PINNED_CAPTION_ICON so a heading is never mistaken for one
# another (tests assert that).
RECENT_CAPTION_ICON = "clock"
# What an inert caption launches: /bin/true exits 0 and does nothing. Only the
# recents heading is inert; the pinned one opens the manager.
NOOP_EXEC = "/bin/true"

# Icon name per entry kind. The names must exist in the usual icon themes
# (Breeze, hicolor): Plasma shows a placeholder for a name it cannot resolve,
# which reads as a broken menu.
#
# Workspaces deliberately have no entry: there is no "workspace" icon in Breeze,
# and recents exclude that kind by default anyway, so they fall back to
# DEFAULT_ICON rather than getting an invented name.
DEFAULT_ICON = "text-x-generic"
ICON_FOR_KIND = {
    ENTRY_FOLDER: "folder",
    ENTRY_FILE: DEFAULT_ICON,
}

# Pinned entries all share one icon, replacing the per-kind one: the star is
# what marks the entry as a pinned one at a glance, which the folder/file icon
# cannot show.
#
# It is Breeze's *outline* star, not the filled one ("starred"): hollow reads as
# a state rather than as a rating, and it stays legible at 16px where a filled
# star's points blur together. Breeze has both at 16/22/24px, and the two are
# drawn to match, so switching between them is a one-word difference.
PINNED_ICON = "non-starred"


def pinned_caption_text(longest_label: int = 0) -> str:
    """The pinned heading, padded so its marker reaches the menu's right edge.

    ``longest_label`` is the length of the longest entry label that will be
    listed alongside it. Short labels get no padding at all: the heading is
    already wider than they are, so adding any would only widen the menu.
    """
    over = max(0, longest_label - PINNED_CAPTION_PAD_FREE)
    pad = " " * round(over * PINNED_CAPTION_PAD_RATIO)
    return f"{PINNED_CAPTION_BASE}{pad}{PINNED_CAPTION_MARKER}"


def excluded_kinds() -> frozenset[str]:
    """Entry kinds to leave out of the recents list."""
    return EXCLUDED_KINDS


def keep_recent(entries: list[MenuEntry]) -> list[MenuEntry]:
    """Drop excluded kinds, preserving MRU order."""
    excluded = excluded_kinds()
    return [entry for entry in entries if entry.kind not in excluded]


def desktop_launcher_command() -> str:
    """``Exec=``-ready launcher for the desktop actions."""
    return format_exec(resolve_cli_argv())


def _sanitize_label(label: str) -> str:
    """Escape characters that are special in desktop-entry values."""
    return label.replace("\\", "\\\\").replace("\n", " ").strip() or "Untitled"


def _action_name(entry: MenuEntry, pinned: bool) -> str:
    prefix = "Pinned" if pinned else "Recent"
    return f"{ACTION_PREFIX}{prefix}-{entry.entry_id}"


# Characters the Desktop Entry Specification reserves inside an Exec argument.
# An argument containing any of them (or whitespace) has to be quoted.
EXEC_RESERVED_CHARS = frozenset(" \t\n\"'\\><~|&;$*#()?!`%")


def format_exec(arguments: list[str]) -> str:
    """Join argv into an ``Exec=`` value, quoting as the spec requires.

    ``shlex.join`` cannot be used here: single quotes are literal in Exec
    values, so quoting is done with double quotes and backslash escapes.
    """
    formatted: list[str] = []
    for argument in arguments:
        if argument and not (EXEC_RESERVED_CHARS & set(argument)):
            formatted.append(argument)
            continue
        escaped = (
            argument.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("`", "\\`")
            .replace("$", "\\$")
        )
        formatted.append(f'"{escaped}"')
    return " ".join(formatted)


def module_source_root() -> Path | None:
    """Directory to put on PYTHONPATH so ``python -m kde_vscode_jumplist`` works.

    Non-``None`` only when this package sits in a plain ``.../<root>/kde_vscode_jumplist``
    layout that can be re-imported by pointing PYTHONPATH at the parent.
    """
    root = Path(__file__).resolve().parent.parent
    return root if (root / MODULE).is_dir() else None


def packaged_cli_path() -> Path | None:
    """The single-file executable built by ``make build``, when present.

    Self-contained, so it is the most dependable thing to bake into an Exec:
    it needs no PYTHONPATH, no virtualenv and no ``PATH`` entry.
    """
    source_root = module_source_root()
    if source_root is None:
        return None
    candidate = source_root.parent / "bin" / APP_NAME
    return candidate if candidate.is_file() else None


def _running_program() -> list[str] | None:
    """The program running right now, if it can be re-run to start the CLI.

    Catches the common cases where the CLI was invoked through a launcher we
    would otherwise have to guess at: the built ``bin/`` executable, or a
    console script. Verification rejects the ones that cannot be re-run (a
    ``python -m`` run leaves ``sys.argv[0]`` pointing at ``__main__.py``).
    """
    if not sys.argv or not sys.argv[0]:
        return None
    program = Path(sys.argv[0])
    if program.is_file() and os.access(program, os.X_OK):
        return [str(program.resolve())]
    return None


def installed_cli_path() -> Path | None:
    """The executable ``install`` placed in the user's bin directory, if any.

    Preferred over everything else but the running program: unlike a build
    artifact in a working tree, it stays valid when the checkout moves.
    """
    candidate = paths.user_bin_dir() / APP_NAME
    return candidate if candidate.is_file() else None


def _candidate_cli_commands(python: str | None = None) -> list[list[str]]:
    """Ways to launch the CLI, most desirable first.

    Installed and built executables are self-contained, so their commands can
    never break later; the interpreter-based fallbacks come last.
    """
    interpreter = python or sys.executable
    candidates: list[list[str]] = []

    running = _running_program()
    if running:
        candidates.append(running)

    installed = installed_cli_path()
    if installed is not None:
        candidates.append([str(installed)])

    console_script = shutil.which(APP_NAME)
    if console_script:
        candidates.append([console_script])

    packaged = packaged_cli_path()
    if packaged is not None:
        candidates.append([str(packaged)])

    candidates.append([interpreter, "-m", MODULE])

    # A source checkout (``make update``) only imports the package because the
    # caller exported PYTHONPATH. Plasma and systemd do not, so bake the import
    # path into the Exec; without this the action would silently do nothing.
    env_binary = shutil.which("env")
    source_root = module_source_root()
    if env_binary and source_root is not None:
        candidates.append([env_binary, f"PYTHONPATH={source_root}", interpreter, "-m", MODULE])

    # ``which`` may well return the installed copy again; probing it twice only
    # costs a subprocess.
    deduplicated: list[list[str]] = []
    seen: set[str] = set()
    for candidate in candidates:
        key = os.path.realpath(candidate[0])
        if key in seen:
            continue
        seen.add(key)
        deduplicated.append(candidate)
    return deduplicated


def launcher_environment() -> dict[str, str]:
    """Environment approximating a Plasma/systemd launch.

    PYTHONPATH/PYTHONHOME are dropped so a candidate is only accepted when it
    works *without* the sync process's own import path.
    """
    environment = dict(os.environ)
    environment.pop("PYTHONPATH", None)
    environment.pop("PYTHONHOME", None)
    return environment


def _command_launches_cli(command: list[str]) -> bool:
    """True when ``command`` starts *this* CLI from a Plasma-like environment.

    The version is compared, not just the exit status: on its own, ``--version``
    is satisfied by any number of unrelated programs (``python``, ``pytest``),
    and baking one of those into an Exec would be worse than no action at all.
    """
    try:
        result = subprocess.run(  # noqa: S603 - argv list, no shell
            [*command, "--version"],
            env=launcher_environment(),
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            timeout=60,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    return result.returncode == 0 and result.stdout.strip() == __version__


def resolve_cli_argv(python: str | None = None) -> list[str]:
    """argv prefix that reliably launches this CLI outside the sync process.

    Candidates are *verified*: a click is useless if the interpreter cannot
    import the package, so broken candidates (e.g. ``/usr/bin/python3`` when
    the package is only on the caller's PYTHONPATH) are skipped.
    """
    candidates = _candidate_cli_commands(python)
    for command in candidates:
        if _command_launches_cli(command):
            return command
    log.error(
        "no working way to launch the CLI found; jump-list actions will do "
        "nothing when clicked (tried: %s)",
        ", ".join(format_exec(command) for command in candidates),
    )
    return candidates[-1]


def _exec_line(entry_id: str, cli_command: str) -> str:
    return f"{cli_command} open {entry_id}"


def _add_caption_group(
    parser: configparser.RawConfigParser,
    action_id: str,
    text: str,
    icon: str,
    exec_line: str = NOOP_EXEC,
) -> str:
    """Write one section caption; returns its action id.

    Inert by default -- ``/bin/true`` exits 0 and does nothing, which is what a
    heading that is only a heading should do. The pinned heading passes its own
    ``exec_line`` instead, because it opens the manager.
    """
    section = f"Desktop Action {action_id}"
    parser.add_section(section)
    parser.set(section, "Name", text)
    parser.set(section, "Icon", icon)
    parser.set(section, "Exec", exec_line)
    return action_id


def build_desktop_content(
    base_content: str,
    pinned: list[MenuEntry],
    recents: list[MenuEntry],
) -> str:
    """Return the full desktop-file text with jump-list actions appended.

    ``pinned`` (the pinned entries) and ``recents`` each become their own block,
    opened by a native separator and a heading ("Pinned Files:" / "Recent
    Files:"). The recents block is omitted when its list is empty; the pinned
    one never is, because its heading is the action that opens the manager.
    The pinned entries come first and in full, then ``recents`` -- a single
    MRU-ordered list of any kind, with the kinds in :func:`excluded_kinds`
    (workspaces) dropped -- fills whatever is left of :data:`TOTAL_ENTRIES`.
    Pinned entries are never filtered, so a pinned workspace still appears.
    """
    parser = configparser.RawConfigParser(strict=False, interpolation=None)
    parser.optionxform = str  # preserve key case
    parser.read_string(base_content)

    if not parser.has_section("Desktop Entry"):
        raise ValueError("vendor desktop file has no [Desktop Entry] section")

    # Remove previously generated actions and their groups, keep others.
    existing_actions = parser.get("Desktop Entry", "Actions", fallback="")
    raw_actions = [a.strip() for a in existing_actions.split(";") if a.strip()]

    def is_ours(name: str) -> bool:
        return name.startswith(ACTION_PREFIX) or name.startswith(LEGACY_ACTION_PREFIXES)

    kept_actions: list[str] = []
    for index, name in enumerate(raw_actions):
        if is_ours(name):
            continue
        if name == SEPARATOR:
            # Only drop the separators we added around our own block, so a
            # vendor-supplied separator elsewhere in Actions= survives.
            after_ours = index > 0 and is_ours(raw_actions[index - 1])
            before_ours = index + 1 < len(raw_actions) and is_ours(raw_actions[index + 1])
            if after_ours or before_ours:
                continue
        kept_actions.append(name)

    for section in list(parser.sections()):
        if section.startswith(_OUR_SECTION_PREFIXES):
            parser.remove_section(section)

    # Verified once per generation pass (spawns a probe process), then reused
    # by every action so all of them are clickable from Plasma.
    cli_command = desktop_launcher_command()

    def add_group(entry: MenuEntry, pinned: bool) -> str:
        """Write one desktop action group; returns its action id."""
        name = _action_name(entry, pinned)
        # KService only recognizes groups named "[Desktop Action <id>]".
        section = f"Desktop Action {name}"
        parser.add_section(section)
        # No "[pinned]" suffix: the block heading and the star icon already say
        # it, and the label stays clean.
        parser.set(section, "Name", _sanitize_label(entry.label))
        icon = PINNED_ICON if pinned else ICON_FOR_KIND.get(entry.kind, DEFAULT_ICON)
        parser.set(section, "Icon", icon)
        parser.set(section, "Exec", _exec_line(entry.entry_id, cli_command))
        return name

    # The pinned entries are listed first and in full (up to the whole budget);
    # the recents get whatever is left of it. Both lists are worked out here so
    # the heading can be sized against every label that will be listed with it --
    # it has to be the widest item for its marker to reach the right edge.
    listed_pinned = pinned[:TOTAL_ENTRIES]
    recent_limit = max(0, TOTAL_ENTRIES - len(listed_pinned))
    listed_recents = keep_recent(recents)[:recent_limit]
    longest_label = max(
        (len(entry.label) for entry in (*listed_pinned, *listed_recents)), default=0
    )

    def pinned_block() -> list[str]:
        """Separator, the pinned heading, and the pinned entries.

        Never empty: the heading is the action that opens the manager, so it is
        the only way to pin anything from the menu, and omitting it because
        nothing is pinned yet would leave no way in. With no pinned entries the
        block is therefore just its separator and heading.
        """
        heading = _add_caption_group(
            parser,
            PINNED_CAPTION_ACTION_ID,
            pinned_caption_text(longest_label),
            PINNED_CAPTION_ICON,
            f"{cli_command} manage",
        )
        entries = [add_group(entry, pinned=True) for entry in listed_pinned]
        return [SEPARATOR, heading, *entries]

    def recents_block() -> list[str]:
        """Separator, heading and recent entries -- empty when nothing recent.

        Excluded kinds (workspaces) were dropped before the limit was applied,
        so the limit counts only entries that actually get listed -- and it is
        what is left of the budget after the pinned block took its share.
        """
        entries = [add_group(entry, pinned=False) for entry in listed_recents]
        if not entries:
            return []
        return [
            SEPARATOR,
            _add_caption_group(
                parser,
                RECENT_CAPTION_ACTION_ID,
                RECENT_CAPTION_TEXT,
                RECENT_CAPTION_ICON,
            ),
            *entries,
        ]

    blocks = (
        [recents_block(), pinned_block()]
        if PINNED_BELOW
        else [pinned_block(), recents_block()]
    )
    new_actions = [action for block in blocks for action in block]

    # Close the list with a separator, so it ends with a line rather than butting
    # up against the bottom of the menu. The pinned heading is always present, so
    # there is always something above it.
    new_actions.append(SEPARATOR)

    all_actions = kept_actions + new_actions
    parser.set("Desktop Entry", "Actions", ";".join(all_actions) + ";")

    output = StringIO()
    parser.write(output, space_around_delimiters=False)
    return GENERATED_MARKER + "\n" + output.getvalue()


def is_generated(path: Path) -> bool:
    """True when a desktop file was written by this tool (not a vendor file).

    Detects the marker comment, and failing that any generated action section,
    so a file that predates the marker is still recognized as ours.
    """
    try:
        content = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    if content.startswith((GENERATED_MARKER, LEGACY_GENERATED_MARKER)):
        return True
    return any(
        f"[{prefix}" in content or f"[Desktop Action {prefix}" in content
        for prefix in (ACTION_PREFIX, *LEGACY_ACTION_PREFIXES)
    )


def write_user_desktop_entry(
    installation_desktop: Path,
    variant: str,
    pinned: list[MenuEntry],
    recents: list[MenuEntry],
) -> Path | None:
    """Copy + extend the vendor desktop file into the user applications dir.

    Returns the written path, or ``None`` when nothing changed / not possible.
    """
    if not installation_desktop.is_file():
        log.warning("vendor desktop file missing: %s", installation_desktop)
        return None

    base_content = installation_desktop.read_text(encoding="utf-8", errors="replace")
    try:
        content = build_desktop_content(base_content, pinned, recents)
    except (ValueError, configparser.Error) as error:
        log.error("cannot generate desktop entry for %s: %s", variant, error)
        return None

    target = paths.user_applications_dir() / installation_desktop.name
    if target.is_file() and target.read_text(encoding="utf-8", errors="replace") == content:
        return None  # unchanged — avoid expensive ksycoca rebuilds

    if installation_desktop.resolve() == target.resolve():
        log.error("refusing to overwrite vendor desktop file %s", target)
        return None

    target.parent.mkdir(parents=True, exist_ok=True)
    atomic_write_text(target, content)
    log.info("wrote %s", target)
    return target


def refresh_service_cache() -> None:
    """Rebuild the KDE service cache so Plasma picks up new actions."""
    for tool in ("kbuildsycoca6", "kbuildsycoca5"):
        binary = shutil.which(tool)
        if binary:
            try:
                subprocess.run(  # noqa: S603
                    [binary],
                    check=False,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    timeout=60,
                )
                log.info("refreshed service cache via %s", tool)
            except (OSError, subprocess.TimeoutExpired) as error:
                log.warning("%s failed: %s", tool, error)
            return
    log.warning("no kbuildsycoca found; Plasma may show stale menu entries")
