#!/usr/bin/env python3
"""Build ``bin/kde-vscode-jumplist``: the whole CLI as one executable file.

The output is a zipapp (``python -m zipapp``): a zip archive with a shebang
line, holding this package, its runtime dependencies and a ``__main__.py``
that calls ``cli.main``. It runs on a bare Python 3 interpreter with nothing
installed, which is what the generated desktop entries need -- no virtualenv,
no ``PYTHONPATH``, no console script on ``PATH``.

Run it via ``make build``.
"""

from __future__ import annotations

import argparse
import importlib.util
import shutil
import subprocess
import sys
import tempfile
import zipapp
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PACKAGE_NAME = "kde_vscode_jumplist"
SOURCE_DIR = REPO_ROOT / "src" / PACKAGE_NAME
DEFAULT_OUTPUT = REPO_ROOT / "bin" / "kde-vscode-jumplist"
SHEBANG = "/usr/bin/env python3"

# Third-party packages the CLI imports at runtime, mirrored from the
# ``dependencies`` list in pyproject.toml (tests/test_build.py asserts they
# agree). They are copied out of the build environment, so no network access
# and no install step are involved.
RUNTIME_DEPENDENCIES = ("tabulate",)

MAIN_TEMPLATE = """\
# Generated by tools/build_zipapp.py - do not edit.
from kde_vscode_jumplist.cli import main

if __name__ == "__main__":
    raise SystemExit(main())
"""

# Stamped into the bundled copy, which has no .git of its own to be asked: the
# About window reads it from there. Values agree with
# kde_vscode_jumplist.buildinfo, which a test keeps them in step with.
GIT_ID_MODULE = "_build_id.py"
GIT_ID_TEMPLATE = """\
# Generated by tools/build_zipapp.py - do not edit.
GIT_ID = {git_id!r}
"""

# Same shape as buildinfo's: git's usual short length, and what is shown when
# there is no commit to name.
GIT_ID_LENGTH = 7
GIT_ID_UNKNOWN = "unknown"
GIT_ID_TIMEOUT = 5

_IGNORED = shutil.ignore_patterns("__pycache__", "*.pyc", "*.pyo", "*.egg-info")


def dependency_path(name: str) -> Path:
    """Location of an installed dependency: its package dir, or module file."""
    spec = importlib.util.find_spec(name)
    if spec is None or spec.origin is None:
        raise SystemExit(
            f"runtime dependency {name!r} is not installed in {sys.executable}; "
            f"install it first (see pyproject.toml)"
        )
    if spec.submodule_search_locations:
        return Path(spec.origin).parent
    return Path(spec.origin)


def git_id(root: Path = REPO_ROOT) -> str:
    """Short id of the commit being built, or ``GIT_ID_UNKNOWN`` with none.

    Read here rather than left to the copy at run time because the archive has no
    repository in it: by the time it is installed, the checkout it was built from
    may have moved on, or be gone.
    """
    try:
        result = subprocess.run(  # noqa: S603 - argv list, no shell
            ["git", "-C", str(root), "rev-parse", f"--short={GIT_ID_LENGTH}", "HEAD"],
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            check=False,
            timeout=GIT_ID_TIMEOUT,
        )
    except (OSError, subprocess.SubprocessError):
        return GIT_ID_UNKNOWN
    return result.stdout.strip() or GIT_ID_UNKNOWN


def stage(destination: Path) -> list[str]:
    """Copy the package, its dependencies and ``__main__`` into ``destination``."""
    shutil.copytree(SOURCE_DIR, destination / PACKAGE_NAME, ignore=_IGNORED)
    # Written into the copy, not the source tree: the checkout stays clean, and
    # an id read from it would go stale with the next commit anyway.
    (destination / PACKAGE_NAME / GIT_ID_MODULE).write_text(
        GIT_ID_TEMPLATE.format(git_id=git_id()), encoding="utf-8"
    )
    staged = [PACKAGE_NAME]
    for name in RUNTIME_DEPENDENCIES:
        source = dependency_path(name)
        shutil.copytree(source, destination / source.name, ignore=_IGNORED)
        staged.append(source.name)
    (destination / "__main__.py").write_text(MAIN_TEMPLATE, encoding="utf-8")
    return staged


def _smoke_test(archive: Path) -> str:
    """Run the built archive the way Plasma will; returns its version output."""
    try:
        result = subprocess.run(  # noqa: S603 - argv list, no shell
            [str(archive), "--version"],
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            check=False,
            timeout=60,
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        raise SystemExit(f"built {archive} but could not run it: {error}") from error
    if result.returncode != 0:
        raise SystemExit(
            f"built {archive} but `--version` exited {result.returncode}: "
            f"{result.stderr.strip()}"
        )
    return result.stdout.strip()


def build(output: Path = DEFAULT_OUTPUT) -> Path:
    """Create the single-file executable at ``output`` and verify it runs."""
    if not SOURCE_DIR.is_dir():
        raise SystemExit(f"package source not found: {SOURCE_DIR}")
    output.parent.mkdir(parents=True, exist_ok=True)

    # Stage in a temporary directory so a failure cannot leave a partial or
    # stale archive in place: it is only written once staging succeeded.
    with tempfile.TemporaryDirectory(prefix="kde-vscode-jumplist-build-") as tmp:
        staging = Path(tmp)
        stage(staging)
        zipapp.create_archive(staging, target=str(output), interpreter=SHEBANG, compressed=True)
    output.chmod(0o755)

    version = _smoke_test(output)
    print(f"built {output} (v{version}, {output.stat().st_size / 1024:.0f} KiB)")
    return output


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"where to write the executable (default: {DEFAULT_OUTPUT})",
    )
    args = parser.parse_args(argv)
    build(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
